[package]
name = "reles-render"
version.workspace = true
edition.workspace = true

[dependencies]
reles-math = { path = "../math" }
reles-world = { path = "../world" }
reles-kernel = { path = "../kernel" }
wgpu.workspace = true
winit.workspace = true
image.workspace = true
bytemuck.workspace = true
serde.workspace = true
toml.workspace = true
tracing.workspace = true
thiserror.workspace = true
anyhow.workspace = true
