name: CI

on:
  push:
    branches: ["wip", "main"]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix:
    name: nix flake check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Format check
        run: nix build --no-link .#checks.x86_64-linux.fmt

      - name: Clippy (-D warnings)
        run: nix build --no-link .#checks.x86_64-linux.clippy

      - name: Units + Integration test
        run: nix build --no-link .#checks.x86_64-linux.unit-tests

      - name: Docs (-D warnings)
        run: nix build --no-link .#checks.x86_64-linux.doc

      - name: Build all binaries
        run: nix build --no-link .#packages.x86_64-linux.default

      - name: Build with opitional features
        run: nix build --no-link .#packages.x86_64-linux.full

      - name: Smoke test
        run: nix build --no-link .#checks.x86_64-linux.content-pipeline-smoke

  content-pipeline:
    name: Content pipeline self test (no original resources)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Pipeline unit tests
        run: |
          nix build --no-link .#checks.x86_64-linux.unit-tests
